import { useState } from 'react'
import { FileText, Upload } from 'lucide-react'
import {
  Button,
  Input,
  Textarea,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  Badge,
  RiskBadge,
  StatusBadge,
  Modal,
  Spinner,
  EmptyState,
  Skeleton,
  SkeletonText,
  SkeletonCard,
} from '@/components/ui'
import { useToast } from '@/contexts/ToastContext'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-12">
      <h2 className="text-lg font-semibold text-slate-900 mb-1">{title}</h2>
      <div className="h-px bg-slate-200 mb-6" />
      {children}
    </section>
  )
}

export default function ComponentsPage() {
  const [modalOpen, setModalOpen] = useState(false)
  const { success, error, warning, info } = useToast()

  return (
    <div className="max-w-4xl mx-auto px-4 py-10">
      <div className="mb-10">
        <h1 className="font-display text-3xl font-semibold text-slate-900 mb-2 tracking-tight">Component Library</h1>
        <p className="text-slate-500">
          Visual reference for all shared UI components. This page is only visible in development.
        </p>
      </div>

      {/* ── Buttons ── */}
      <Section title="Button">
        <div className="flex flex-wrap gap-3">
          <Button variant="primary">Primary</Button>
          <Button variant="secondary">Secondary</Button>
          <Button variant="ghost">Ghost</Button>
          <Button variant="danger">Danger</Button>
        </div>
        <div className="flex flex-wrap gap-3 mt-4">
          <Button variant="primary" size="sm">Small</Button>
          <Button variant="primary" size="md">Medium</Button>
          <Button variant="primary" size="lg">Large</Button>
        </div>
        <div className="flex flex-wrap gap-3 mt-4">
          <Button variant="primary" loading>Loading</Button>
          <Button variant="primary" disabled>Disabled</Button>
        </div>
      </Section>

      {/* ── Inputs ── */}
      <Section title="Input">
        <div className="grid sm:grid-cols-2 gap-4">
          <Input label="Email address" type="email" placeholder="you@example.com" required />
          <Input label="With error" defaultValue="bad-email" error="Please enter a valid email." />
          <Input label="With hint" placeholder="Search…" hint="Press Enter to search." />
          <Input label="Disabled" defaultValue="Not editable" disabled />
        </div>
      </Section>

      {/* ── Textarea ── */}
      <Section title="Textarea">
        <div className="grid sm:grid-cols-2 gap-4">
          <Textarea label="Message" placeholder="Type your message…" />
          <Textarea label="With error" error="This field is required." />
        </div>
      </Section>

      {/* ── Card ── */}
      <Section title="Card">
        <div className="grid sm:grid-cols-2 gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Document Summary</CardTitle>
              <CardDescription>Automatically generated by LexAI</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-slate-600">
                This is a service agreement between Acme Corp and the client dated January 2025.
              </p>
            </CardContent>
          </Card>
          <Card padding="lg">
            <p className="text-sm text-slate-700 font-medium mb-1">Large padding variant</p>
            <p className="text-sm text-slate-500">Extra breathing room for prominent content.</p>
          </Card>
          <Card interactive>
            <p className="text-sm text-slate-700 font-medium mb-1">Interactive variant</p>
            <p className="text-sm text-slate-500">Hover to see the lift + shadow transition.</p>
          </Card>
        </div>
      </Section>

      {/* ── Badges ── */}
      <Section title="Badge">
        <div className="flex flex-wrap gap-2 mb-4">
          <Badge variant="default">Default</Badge>
          <Badge variant="success">Success</Badge>
          <Badge variant="warning">Warning</Badge>
          <Badge variant="error">Error</Badge>
          <Badge variant="info">Info</Badge>
          <Badge variant="muted">Muted</Badge>
        </div>
        <div className="flex flex-wrap gap-2 mb-4">
          <span className="text-xs text-slate-400 self-center mr-1">Risk severity:</span>
          <RiskBadge severity="HIGH" />
          <RiskBadge severity="MEDIUM" />
          <RiskBadge severity="LOW" />
        </div>
        <div className="flex flex-wrap gap-2">
          <span className="text-xs text-slate-400 self-center mr-1">Document status:</span>
          <StatusBadge status="UPLOADED" />
          <StatusBadge status="TEXT_EXTRACTED" />
          <StatusBadge status="ANALYZED" />
          <StatusBadge status="FAILED" />
        </div>
      </Section>

      {/* ── Spinner ── */}
      <Section title="Spinner">
        <div className="flex items-center gap-6">
          <Spinner size="sm" />
          <Spinner size="md" className="text-primary-900" />
          <Spinner size="lg" className="text-primary-900" />
        </div>
      </Section>

      {/* ── Modal ── */}
      <Section title="Modal">
        <Button onClick={() => setModalOpen(true)} variant="secondary">
          Open modal
        </Button>
        <Modal
          open={modalOpen}
          onClose={() => setModalOpen(false)}
          title="Confirm action"
          description="This is an example modal dialog."
        >
          <p className="text-sm text-slate-600 mb-6">
            Modals trap focus, close on Escape, and are rendered in a portal.
          </p>
          <div className="flex justify-end gap-3">
            <Button variant="secondary" onClick={() => setModalOpen(false)}>
              Cancel
            </Button>
            <Button onClick={() => setModalOpen(false)}>Confirm</Button>
          </div>
        </Modal>
      </Section>

      {/* ── Toast ── */}
      <Section title="Toast">
        <div className="flex flex-wrap gap-3">
          <Button variant="secondary" size="sm" onClick={() => success('Saved!', 'Your changes were saved successfully.')}>
            Success toast
          </Button>
          <Button variant="secondary" size="sm" onClick={() => error('Upload failed', 'Please try again or contact support.')}>
            Error toast
          </Button>
          <Button variant="secondary" size="sm" onClick={() => warning('Almost at your limit', 'You have used 2 of 3 free documents.')}>
            Warning toast
          </Button>
          <Button variant="secondary" size="sm" onClick={() => info('Analysis in progress', 'This usually takes 10–30 seconds.')}>
            Info toast
          </Button>
        </div>
      </Section>

      {/* ── EmptyState ── */}
      <Section title="EmptyState">
        <Card>
          <EmptyState
            icon={<FileText className="w-6 h-6" />}
            title="No documents yet"
            description="Upload your first legal document to get started with a plain-English analysis."
            action={
              <Button>
                <Upload className="w-4 h-4" />
                Upload a document
              </Button>
            }
          />
        </Card>
      </Section>

      {/* ── Skeleton ── */}
      <Section title="Skeleton">
        <div className="grid sm:grid-cols-2 gap-4">
          <div className="space-y-3">
            <Skeleton className="h-6 w-1/2" />
            <SkeletonText lines={4} />
          </div>
          <SkeletonCard />
        </div>
      </Section>
    </div>
  )
}
